catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.24
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
  "@undecaf/zbar-wasm": "^0.11.0"
patchedDependencies:
  "@undecaf/barcode-detector-polyfill": setup/patches/@undecaf__barcode-detector-polyfill.patch
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
